Open5GS daemon v1.2.4

04/28 00:28:28.108: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 00:28:28.108: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 00:28:28.264: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 00:28:28.265: [gtp] INFO: gtp_server() [192.168.26.20]:2123 (../lib/gtp/path.c:32)
04/28 00:28:28.265: [gtp] INFO: gtp_connect() [192.168.26.30]:2123 (../lib/gtp/path.c:59)
04/28 00:28:28.266: [mme] INFO: s1ap_server() [192.168.26.20]:36412 (../src/mme/s1ap-sctp.c:57)
04/28 00:28:30.312: [diam] INFO: CONNECTED TO 'hss.localdomain' (SCTP,soc#10): (../lib/diameter/common/logger.c:108)
04/28 00:28:42.782: [mme] INFO: eNB-S1 accepted[192.168.26.60]:44226 in s1_path module (../src/mme/s1ap-sctp.c:109)
04/28 00:28:42.783: [mme] INFO: eNB-S1 accepted[192.168.26.60] in master_sm module (../src/mme/mme-sm.c:166)
04/28 00:28:42.784: [mme] INFO: Added a eNB. Number of eNBs is now 1 (../src/mme/mme-context.c:68)
04/28 00:29:28.935: [mme] INFO: Added a UE. Number of UEs is now 1 (../src/mme/mme-context.c:58)
04/28 00:29:29.000: [mme] INFO: Added a session. Number of sessions is now 1 (../src/mme/mme-context.c:79)
04/28 00:30:29.106: [mme] INFO: Removed a UE. Number of UEs is now 0 (../src/mme/mme-context.c:63)
04/28 00:33:30.009: [mme] INFO: eNB-S1[192.168.26.60] connection refused!!! (../src/mme/mme-sm.c:216)
04/28 00:33:30.009: [mme] INFO: Removed a eNB. Number of eNBs is now 0 (../src/mme/mme-context.c:73)
Open5GS daemon v1.2.4

04/28 00:46:12.801: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 00:46:12.801: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 00:46:12.994: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 00:46:12.994: [gtp] INFO: gtp_server() [192.168.26.20]:2123 (../lib/gtp/path.c:32)
04/28 00:46:12.995: [gtp] INFO: gtp_connect() [192.168.26.30]:2123 (../lib/gtp/path.c:59)
04/28 00:46:12.995: [mme] INFO: s1ap_server() [192.168.26.20]:36412 (../src/mme/s1ap-sctp.c:57)
04/28 00:46:12.999: [diam] INFO: CONNECTED TO 'hss.localdomain' (SCTP,soc#13): (../lib/diameter/common/logger.c:108)
04/28 00:46:27.930: [mme] INFO: eNB-S1 accepted[192.168.26.60]:57113 in s1_path module (../src/mme/s1ap-sctp.c:109)
04/28 00:46:27.931: [mme] INFO: eNB-S1 accepted[192.168.26.60] in master_sm module (../src/mme/mme-sm.c:166)
04/28 00:46:27.932: [mme] INFO: Added a eNB. Number of eNBs is now 1 (../src/mme/mme-context.c:68)
04/28 00:52:35.535: [mme] INFO: Added a UE. Number of UEs is now 1 (../src/mme/mme-context.c:58)
04/28 00:52:35.600: [mme] INFO: Added a session. Number of sessions is now 1 (../src/mme/mme-context.c:79)
04/28 00:53:35.700: [mme] INFO: Removed a UE. Number of UEs is now 0 (../src/mme/mme-context.c:63)
04/28 01:18:47.181: [mme] INFO: eNB-S1[192.168.26.60] connection refused!!! (../src/mme/mme-sm.c:216)
04/28 01:18:47.182: [mme] INFO: Removed a eNB. Number of eNBs is now 0 (../src/mme/mme-context.c:73)
Open5GS daemon v1.2.4

04/28 01:28:31.884: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 01:28:31.884: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 01:28:32.159: [diam] ERROR: ../subprojects/freeDiameter/libfdcore/sctp.c:835 ERROR: in '(sctp_bindx(*sock, sar, count, 0x01))' :	Cannot assign requested address (../lib/diameter/common/init.c:116)
04/28 01:28:32.159: [diam] ERROR: ../subprojects/freeDiameter/libfdcore/cnxctx.c:181 ERROR: in '(fd_sctp_create_bind_server( &cnx->cc_socket, cnx->cc_family, ep_list, port ))' :	Cannot assign requested address (../lib/diameter/common/init.c:116)
04/28 01:28:32.159: [diam] ERROR: ../subprojects/freeDiameter/libfdcore/server.c:355 ERROR: in '(s->conn = fd_cnx_serv_sctp(fd_g_config->cnf_port, empty_conf_ep ? ((void *)0) : &fd_g_config->cnf_endpoints))' :	Transport endpoint is not connected (../lib/diameter/common/init.c:116)
04/28 01:28:32.159: [diam] ERROR: ../subprojects/freeDiameter/libfdcore/core.c:300 ERROR: in '((fd_servers_start()))' :	Transport endpoint is not connected (../lib/diameter/common/init.c:116)
04/28 01:28:32.159: [diam] ERROR: ../lib/diameter/common/init.c:62 ERROR: in '(fd_core_start())' :	Transport endpoint is not connected (../lib/diameter/common/init.c:116)
04/28 01:28:32.270: [mme] FATAL: mme_fd_init: Assertion `ret == OGS_OK' failed. (../src/mme/mme-fd-path.c:1092)
Open5GS daemon v1.2.4

04/28 01:41:15.998: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 01:41:15.998: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 01:41:16.200: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 01:41:16.201: [sock] ERROR: socket bind(2) [192.168.26.20]:2123 failed (99:Cannot assign requested address) (../lib/core/ogs-socket.c:111)
04/28 01:41:16.201: [sock] ERROR: udp_server() [192.168.26.20]:2123 failed (99:Cannot assign requested address) (../lib/core/ogs-udp.c:68)
04/28 01:41:16.201: [gtp] FATAL: ogs_gtp_server: Assertion `gtp' failed. (../lib/gtp/path.c:29)
Open5GS daemon v1.2.4

04/28 01:45:44.338: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 01:45:44.338: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 01:45:44.456: [gtp] INFO: gtp_server() [10.128.0.20]:2123 (../lib/gtp/path.c:32)
04/28 01:45:44.456: [gtp] INFO: gtp_connect() [10.128.0.21]:2123 (../lib/gtp/path.c:59)
04/28 01:45:44.456: [mme] INFO: s1ap_server() [10.128.0.20]:36412 (../src/mme/s1ap-sctp.c:57)
04/28 01:45:44.456: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 01:45:44.460: [diam] INFO: CONNECTED TO 'hss.localdomain' (SCTP,soc#12): (../lib/diameter/common/logger.c:108)
Open5GS daemon v1.2.4

04/28 02:30:38.966: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 02:30:38.967: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 02:30:39.198: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 02:30:39.199: [gtp] INFO: gtp_server() [10.128.0.20]:2123 (../lib/gtp/path.c:32)
04/28 02:30:39.199: [gtp] INFO: gtp_connect() [10.128.0.21]:2123 (../lib/gtp/path.c:59)
04/28 02:30:39.199: [mme] INFO: s1ap_server() [10.128.0.20]:36412 (../src/mme/s1ap-sctp.c:57)
04/28 02:30:39.244: [diam] INFO: CONNECTED TO 'hss.localdomain' (SCTP,soc#13): (../lib/diameter/common/logger.c:108)
Open5GS daemon v1.2.4

04/28 02:34:08.959: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 02:34:08.959: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 02:34:09.136: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 02:34:09.136: [gtp] INFO: gtp_server() [10.128.0.20]:2123 (../lib/gtp/path.c:32)
04/28 02:34:09.137: [gtp] INFO: gtp_connect() [10.128.0.21]:2123 (../lib/gtp/path.c:59)
04/28 02:34:09.137: [mme] INFO: s1ap_server() [10.128.0.20]:36412 (../src/mme/s1ap-sctp.c:57)
04/28 02:34:09.139: [diam] INFO: CONNECTED TO 'hss.localdomain' (SCTP,soc#10): (../lib/diameter/common/logger.c:108)
Open5GS daemon v1.2.4

04/28 23:19:17.340: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 23:19:17.340: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 23:19:17.545: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 23:19:17.546: [gtp] INFO: gtp_server() [10.128.0.20]:2123 (../lib/gtp/path.c:32)
04/28 23:19:17.546: [gtp] INFO: gtp_connect() [10.128.0.21]:2123 (../lib/gtp/path.c:59)
04/28 23:19:17.548: [mme] INFO: s1ap_server() [10.128.0.20]:36412 (../src/mme/s1ap-sctp.c:57)
04/28 23:19:17.549: [diam] INFO: CONNECTED TO 'hss.localdomain' (SCTP,soc#13): (../lib/diameter/common/logger.c:108)
04/28 23:26:34.869: [diam] ERROR: ../subprojects/freeDiameter/libfdcore/p_psm.c:287 'STATE_OPEN'	-> 'STATE_CLOSED'	'hss.localdomain' (../lib/diameter/common/init.c:116)
Open5GS daemon v1.2.4

04/28 23:27:42.856: [app] INFO: Configuration: '/usr/local/etc/open5gs/mme.yaml' (../src/main.c:54)
04/28 23:27:42.856: [app] INFO: File Logging: '/usr/local/var/log/open5gs/mme.log' (../src/main.c:57)
04/28 23:27:43.044: [app] INFO: MME initialize...done (../src/mme/app-init.c:33)
04/28 23:27:43.044: [gtp] INFO: gtp_server() [10.128.0.20]:2123 (../lib/gtp/path.c:32)
04/28 23:27:43.045: [gtp] INFO: gtp_connect() [10.128.0.21]:2123 (../lib/gtp/path.c:59)
04/28 23:27:43.045: [mme] INFO: s1ap_server() [10.128.0.20]:36412 (../src/mme/s1ap-sctp.c:57)
04/28 23:27:45.339: [diam] INFO: CONNECTED TO 'hss.localdomain' (SCTP,soc#6): (../lib/diameter/common/logger.c:108)
04/28 23:27:58.074: [mme] INFO: eNB-S1 accepted[10.128.0.24]:32800 in s1_path module (../src/mme/s1ap-sctp.c:109)
04/28 23:27:58.075: [mme] INFO: eNB-S1 accepted[10.128.0.24] in master_sm module (../src/mme/mme-sm.c:166)
04/28 23:27:58.076: [mme] INFO: Added a eNB. Number of eNBs is now 1 (../src/mme/mme-context.c:68)
04/28 23:28:43.835: [mme] INFO: Added a UE. Number of UEs is now 1 (../src/mme/mme-context.c:58)
04/28 23:28:43.903: [mme] INFO: Added a session. Number of sessions is now 1 (../src/mme/mme-context.c:79)
04/28 23:29:44.024: [mme] INFO: Removed a UE. Number of UEs is now 0 (../src/mme/mme-context.c:63)
